[project]
name = "feature_extractor"
version = "0.1.0"
description = "Computer vision feature extraction for images on edge devices."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["xfeat", "sp"]
